apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  ports:
    - port: 80
      nodePort: 31000
  selector:
    type: html
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-html
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: html-environment 
  labels:
    app: webserver
    type: html
spec:
  selector:
    matchLabels:
      type: html
  template:
    metadata:
      labels:
        app: webserver
        type: html
    spec:
      containers:
      - image: httpd
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webserver-pv
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: webserver-pv
        persistentVolumeClaim:
          claimName: pvc-html
